# `NUMPY`   

- Numpy stands for Numerical Python
- Numpy is general purpose array processing package
- It provides a high performance multi dimensional array object and tools for working with these arrays
- Used for mathematical and scientific computations
- Also provides 'linalg' module which contains functions like (det,eignorm) to apply linear algebra on numpy arrays
- Numpy array is most widely used object of numpy library

### Installation of `Numpy Library`

In [1]:
# Following command is used to install the NUMPY 

!pip install numpy

### Imoprting the `Numpy Library`

In [3]:
# Following command is used to import the NUMPY LIBRARY in jupyter notebook

import numpy as np  

# Here the "np" is used as an alias for numpy means np is used as short name for "numpy"

### NUMPY ARRAY

- Numpy array looks similar to list
- It is a grid of index , values by positive integer
- It generally contains numeric values, However it can also contain strings
- Works faster than list as it is a homogeneous object
- It can be multidimensional

#### CREATING AN ARRAY

##### - np.array() Function

- `np.array()` function is used to create an numpy array 

In [11]:
##################### CREATING AN 1-D ARRAY #####################

a = np.array([1,2,3,4,-5])
b = np.array([1,2,3,4.0,-5])
print("Array(a) = ",a,"Array(b) = ",b)

# If one of the value in the array is float type the the array will match all values to float

Array(a) =  [ 1  2  3  4 -5] Array(b) =  [ 1.  2.  3.  4. -5.]


In [16]:
##################### CREATING AN 2-D ARRAY #####################

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2.0,3],[4,5,-6]])
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 1.,  2.,  3.],
        [ 4.,  5., -6.]]))

In [18]:
##################### CREATING AN 3-D ARRAY #####################
a = np.array([[[1,2,3],[4,5,6]],[[1,0,3],[4,5,-6]]])
b = np.array([[[1,2.0,3],[4,5,-6]],[[1,2,3],[4,5,6]]])
a,b

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 1,  0,  3],
         [ 4,  5, -6]]]),
 array([[[ 1.,  2.,  3.],
         [ 4.,  5., -6.]],
 
        [[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]]]))

### RANDOM METHODS

##### - np.random.random() [np.Function.Method( )]

- This function,methode is used to create the random array
- Return random `floats` in the half-open interval [0.0, 1.0).

In [19]:
##################### CREATING AN 1-D RANDOM ARRAY #####################

np.random.random(4)  # Here 4 defines the number of element to be generated in array
                     # syntax :- random(size=None)
    
#Return random floats in the half-open interval [0.0, 1.0).

array([0.67489679, 0.57160807, 0.33525131, 0.35630351])

In [22]:
# If size of array is not defined the it will return any one float integer in between 0.0 to 1.0

np.random.random()

0.38950626420970713

In [25]:
##################### CREATING AN 2-D RANDOM ARRAY #####################

np.random.random(3,3)

TypeError: random() takes at most 1 positional argument (2 given)

ERROR >>

Here the `Random()` Method takes only one positionl arguments suppose with the help of `random.random()` we can generate an 1-D array very easily.
But suppose if we want to generate 2-D array we are not able to generate as `random.random()` accepts only one one argument
To generate 2-D array we have to past a list or a tuple in `random.random()` which defines the shape of an array.

In [32]:
##################### CREATING AN 2-D RANDOM ARRAY #####################

np.random.random([2,3])

# Here the 1st element in list defines the rows of array 
# Here the 2nd element in list defines the columns of array 

array([[0.22054854, 0.00966556, 0.3921653 ],
       [0.6009954 , 0.25556126, 0.69737447]])

In [31]:
##################### CREATING AN 3-D RANDOM ARRAY #####################

np.random.random([2,2,3])

# Here the first element in list defines the set of array
# Here the second element in list defines the rows in each set of array
# Here the third element in the list defines the columns in each set of array

array([[[0.23596599, 0.89390256, 0.35488891],
        [0.95508972, 0.1765272 , 0.2198424 ]],

       [[0.0315524 , 0.58943695, 0.69017975],
        [0.66939821, 0.15360103, 0.26819427]]])

##### - np.random.rand() [np.Function.Method( )]

- This function,method is used to create an array of random numbers of  the given shape between (0.0,1.0)
- The dimensions of the returned array, must be non-negative.
- If no argument is given a single Python `float` is returned.

In [34]:
##################### CREATING AN 1-D RANDOM ARRAY #####################

np.random.rand(4)    # Here 4 defines the number of element to be generated in array
                     # syntax :- rand(size=None)

array([0.25953998, 0.27225057, 0.87364586, 0.65767835])

In [35]:
# If size of array is not defined the it will return any one float integer in between 0.0 to 1.0

np.random.rand()

0.8230534963234237

In [41]:
##################### CREATING AN 2-D RANDOM ARRAY #####################

np.random.rand(2,3)  

# Here the 1st element in list defines the rows of array 
# Here the 2nd element in list defines the columns of array

array([[0.54980592, 0.05856422, 0.52618541],
       [0.1123    , 0.24051699, 0.09431991]])

Here there is no any need of defining the array dimension and shape of 2-D/3-D in a list as the `rand()` method directly except the element in the form of tuple

In [40]:
##################### CREATING AN 3-D RANDOM ARRAY #####################

np.random.rand(2,2,3)

# Here the first element in list defines the set of array
# Here the second element in list defines the rows in each set of array
# Here the third element in the list defines the columns in each set of array

array([[[0.62543294, 0.219221  , 0.80998909],
        [0.8407319 , 0.08282947, 0.39681631]],

       [[0.06407533, 0.31329649, 0.41113281],
        [0.41180491, 0.71275346, 0.69685572]]])

##### np.random.randn() [np.Function.Method( )]

- `np.random.randn()` returns the positive as well as also it can returns the negative random values above aor below zero.  
- If no argument is given a single Python `float` is returned.

In [48]:
##################### CREATING AN 1-D RANDOM ARRAY #####################

np.random.randn(4)   # Here 4 defines the number of element to be generated in array
                     # syntax :- rand(size=None)

array([-1.59881296,  0.75677288, -0.05764282,  1.13894535])

In [49]:
# If size of array is not defined the it will return any one float integer in between 0.0 to 1.0

np.random.randn()

-1.669209089546741

In [51]:
##################### CREATING AN 2-D RANDOM ARRAY #####################

np.random.randn(2,3)  

# Here the 1st element in list defines the rows of array 
# Here the 2nd element in list defines the columns of array

array([[-0.30824331,  0.57858086, -1.26077969],
       [ 0.50358989,  0.33117219, -0.99256086]])

Here there is no any need of defining the array dimension and shape of 2-D/3-D in a list as the `rand()` method directly except the element in the form of tuple

In [52]:
##################### CREATING AN 3-D RANDOM ARRAY #####################

np.random.randn(2,2,3)

# Here the first element in list defines the set of array
# Here the second element in list defines the rows in each set of array
# Here the third element in the list defines the columns in each set of array

array([[[-1.39339889,  0.37055144,  0.44297836],
        [ 0.47322319,  1.29300736,  0.5478085 ]],

       [[ 1.17110938,  1.61270812,  0.4753949 ],
        [ 1.96605698, -1.16640566, -0.20586683]]])

##### - np.random.randint() [np.Function.Method( )] 

- The `random.randint()` function,methode returns the random integer values from low(inclusive) to high(inclusive)

In [60]:
np.random.randint(2,10)

# Here it returns only one random integer value between 2 to 10
# The 2,10 defines the range of numbers from which we want an random values

2

In [66]:
##################### CREATING AN 1-D RANDOM ARRAY #####################

np.random.randint(low= 1, high = 10, size = 12)

# Here it returns 12 random integer value between 1 to 10
# low defines the start value of range
# high defines the end value of range
# size defines the number of element required in the array

array([1, 8, 8, 9, 1, 8, 7, 5, 4, 1, 1, 6])

In [68]:
np.random.randint(1,10,12)

array([2, 1, 5, 2, 3, 9, 6, 6, 2, 4, 2, 5])

In [70]:
np.random.randint()

TypeError: randint() takes at least 1 positional argument (0 given)

In [81]:
##################### CREATING AN 2-D RANDOM ARRAY #####################

np.random.randint(low= 1, high = 10, size = (2,3))

# low defines the start value of range
# high defines the end value of range
# # size defines the shape and dimension the of array with rows and columns

array([[7, 9, 1],
       [9, 6, 7]])

In [82]:
np.random.randint(1,10,(2,3))

array([[2, 4, 4],
       [8, 8, 6]])

In [83]:
##################### CREATING AN 3-D RANDOM ARRAY #####################

np.random.randint(low = 1, high = 10, size = [2,2,3])
# low defines the start value of range
# high defines the end value of range
# size defines the shape and dimension the of array with set, rows and columns

array([[[1, 5, 9],
        [3, 7, 2]],

       [[5, 2, 4],
        [4, 9, 1]]])

In [84]:
np.random.randint(1,10,(2,2,3))

array([[[1, 9, 2],
        [1, 5, 5]],

       [[8, 4, 6],
        [5, 1, 4]]])