# `NUMPY`   

- Numpy stands for Numerical Python
- Numpy is general purpose array processing package
- It provides a high performance multi dimensional array object and tools for working with these arrays
- Used for mathematical and scientific computations
- Also provides 'linalg' module which contains functions like (det,eignorm) to apply linear algebra on numpy arrays
- Numpy array is most widely used object of numpy library

### Installation of `Numpy Library`

In [1]:
# Following command is used to install the NUMPY 

!pip install numpy

### Imoprting the `Numpy Library`

In [3]:
# Following command is used to import the NUMPY LIBRARY in jupyter notebook

import numpy as np  

# Here the "np" is used as an alias for numpy means np is used as short name for "numpy"

### NUMPY ARRAY

- Numpy array looks similar to list
- It is a grid of index , values by positive integer
- It generally contains numeric values, However it can also contain strings
- Works faster than list as it is a homogeneous object
- It can be multidimensional

#### CREATING AN ARRAY

##### - np.array() Function

- `np.array()` function is used to create an numpy array 

In [11]:
##################### CREATING AN 1-D ARRAY #####################

a = np.array([1,2,3,4,-5])
b = np.array([1,2,3,4.0,-5])
print("Array(a) = ",a,"Array(b) = ",b)

# If one of the value in the array is float type the the array will match all values to float

Array(a) =  [ 1  2  3  4 -5] Array(b) =  [ 1.  2.  3.  4. -5.]


In [16]:
##################### CREATING AN 2-D ARRAY #####################

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2.0,3],[4,5,-6]])
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 1.,  2.,  3.],
        [ 4.,  5., -6.]]))

In [18]:
##################### CREATING AN 3-D ARRAY #####################
a = np.array([[[1,2,3],[4,5,6]],[[1,0,3],[4,5,-6]]])
b = np.array([[[1,2.0,3],[4,5,-6]],[[1,2,3],[4,5,6]]])
a,b

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 1,  0,  3],
         [ 4,  5, -6]]]),
 array([[[ 1.,  2.,  3.],
         [ 4.,  5., -6.]],
 
        [[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]]]))

### RANDOM METHODS

##### - np.random.random() [np.Function.Method( )]

- This function,methode is used to create the random array
- Return random `floats` in the half-open interval [0.0, 1.0).

In [19]:
##################### CREATING AN 1-D RANDOM ARRAY #####################

np.random.random(4)  # Here 4 defines the number of element to be generated in array
                     # syntax :- random(size=None)
    
#Return random floats in the half-open interval [0.0, 1.0).

array([0.67489679, 0.57160807, 0.33525131, 0.35630351])

In [22]:
# If size of array is not defined the it will return any one float integer in between 0.0 to 1.0

np.random.random()

0.38950626420970713

In [25]:
##################### CREATING AN 2-D RANDOM ARRAY #####################

np.random.random(3,3)

TypeError: random() takes at most 1 positional argument (2 given)

ERROR >>

Here the `Random()` Method takes only one positionl arguments suppose with the help of `random.random()` we can generate an 1-D array very easily.
But suppose if we want to generate 2-D array we are not able to generate as `random.random()` accepts only one one argument
To generate 2-D array we have to past a list or a tuple in `random.random()` which defines the shape of an array.

In [32]:
##################### CREATING AN 2-D RANDOM ARRAY #####################

np.random.random([2,3])

# Here the 1st element in list defines the rows of array 
# Here the 2nd element in list defines the columns of array 

array([[0.22054854, 0.00966556, 0.3921653 ],
       [0.6009954 , 0.25556126, 0.69737447]])

In [31]:
##################### CREATING AN 3-D RANDOM ARRAY #####################

np.random.random([2,2,3])

# Here the first element in list defines the set of array
# Here the second element in list defines the rows in each set of array
# Here the third element in the list defines the columns in each set of array

array([[[0.23596599, 0.89390256, 0.35488891],
        [0.95508972, 0.1765272 , 0.2198424 ]],

       [[0.0315524 , 0.58943695, 0.69017975],
        [0.66939821, 0.15360103, 0.26819427]]])

##### - np.random.rand() [np.Function.Method( )]

- This function,method is used to create an array of random numbers of  the given shape between (0.0,1.0)
- The dimensions of the returned array, must be non-negative.
- If no argument is given a single Python `float` is returned.

In [34]:
##################### CREATING AN 1-D RANDOM ARRAY #####################

np.random.rand(4)    # Here 4 defines the number of element to be generated in array
                     # syntax :- rand(size=None)

array([0.25953998, 0.27225057, 0.87364586, 0.65767835])

In [35]:
# If size of array is not defined the it will return any one float integer in between 0.0 to 1.0

np.random.rand()

0.8230534963234237

In [41]:
##################### CREATING AN 2-D RANDOM ARRAY #####################

np.random.rand(2,3)  

# Here the 1st element in list defines the rows of array 
# Here the 2nd element in list defines the columns of array

array([[0.54980592, 0.05856422, 0.52618541],
       [0.1123    , 0.24051699, 0.09431991]])

Here there is no any need of defining the array dimension and shape of 2-D/3-D in a list as the `rand()` method directly except the element in the form of tuple

In [40]:
##################### CREATING AN 3-D RANDOM ARRAY #####################

np.random.rand(2,2,3)

# Here the first element in list defines the set of array
# Here the second element in list defines the rows in each set of array
# Here the third element in the list defines the columns in each set of array

array([[[0.62543294, 0.219221  , 0.80998909],
        [0.8407319 , 0.08282947, 0.39681631]],

       [[0.06407533, 0.31329649, 0.41113281],
        [0.41180491, 0.71275346, 0.69685572]]])

##### np.random.randn() [np.Function.Method( )]

- `np.random.randn()` returns the positive as well as also it can returns the negative random values above aor below zero.  
- If no argument is given a single Python `float` is returned.

In [48]:
##################### CREATING AN 1-D RANDOM ARRAY #####################

np.random.randn(4)   # Here 4 defines the number of element to be generated in array
                     # syntax :- rand(size=None)

array([-1.59881296,  0.75677288, -0.05764282,  1.13894535])

In [49]:
# If size of array is not defined the it will return any one float integer in between 0.0 to 1.0

np.random.randn()

-1.669209089546741

In [51]:
##################### CREATING AN 2-D RANDOM ARRAY #####################

np.random.randn(2,3)  

# Here the 1st element in list defines the rows of array 
# Here the 2nd element in list defines the columns of array

array([[-0.30824331,  0.57858086, -1.26077969],
       [ 0.50358989,  0.33117219, -0.99256086]])

Here there is no any need of defining the array dimension and shape of 2-D/3-D in a list as the `rand()` method directly except the element in the form of tuple

In [52]:
##################### CREATING AN 3-D RANDOM ARRAY #####################

np.random.randn(2,2,3)

# Here the first element in list defines the set of array
# Here the second element in list defines the rows in each set of array
# Here the third element in the list defines the columns in each set of array

array([[[-1.39339889,  0.37055144,  0.44297836],
        [ 0.47322319,  1.29300736,  0.5478085 ]],

       [[ 1.17110938,  1.61270812,  0.4753949 ],
        [ 1.96605698, -1.16640566, -0.20586683]]])

##### - np.random.randint() [np.Function.Method( )] 

- The `random.randint()` function,methode returns the random integer values from low(inclusive) to high(inclusive)

In [60]:
np.random.randint(2,10)

# Here it returns only one random integer value between 2 to 10
# The 2,10 defines the range of numbers from which we want an random values

2

In [66]:
##################### CREATING AN 1-D RANDOM ARRAY #####################

np.random.randint(low= 1, high = 10, size = 12)

# Here it returns 12 random integer value between 1 to 10
# low defines the start value of range
# high defines the end value of range
# size defines the number of element required in the array

array([1, 8, 8, 9, 1, 8, 7, 5, 4, 1, 1, 6])

In [68]:
np.random.randint(1,10,12)

array([2, 1, 5, 2, 3, 9, 6, 6, 2, 4, 2, 5])

In [70]:
np.random.randint()

TypeError: randint() takes at least 1 positional argument (0 given)

In [81]:
##################### CREATING AN 2-D RANDOM ARRAY #####################

np.random.randint(low= 1, high = 10, size = (2,3))

# low defines the start value of range
# high defines the end value of range
# # size defines the shape and dimension the of array with rows and columns

array([[7, 9, 1],
       [9, 6, 7]])

In [82]:
np.random.randint(1,10,(2,3))

array([[2, 4, 4],
       [8, 8, 6]])

In [83]:
##################### CREATING AN 3-D RANDOM ARRAY #####################

np.random.randint(low = 1, high = 10, size = [2,2,3])
# low defines the start value of range
# high defines the end value of range
# size defines the shape and dimension the of array with set, rows and columns

array([[[1, 5, 9],
        [3, 7, 2]],

       [[5, 2, 4],
        [4, 9, 1]]])

In [84]:
np.random.randint(1,10,(2,2,3))

array([[[1, 9, 2],
        [1, 5, 5]],

       [[8, 4, 6],
        [5, 1, 4]]])

### NUMPY FUNCTIONS

##### - np.arange() [np.Function()]

- Return as many possible evenly spaced values within a given interval, the interval include `start` but exclude `stop`
- For integer arguments the function is equivalent to the built-in `range` function, but returns an ndarray rather than a list.
- Returns only 1-D array

In [103]:
np.arange(start = 0, stop = 10, step = 2, dtype = int)

# Here start defines the start value of the range
# Here stop defines the stop value of the range
# Here step defines the difference between the two elements in the array which is to be generated
# Here dtype defines the data type of the returned array

array([0, 2, 4, 6, 8])

In [100]:
np.arange(10,20,2,float)

array([10., 12., 14., 16., 18.])

When using a non-integer step, such as 0.1, the results will often not be consistent.  It is better to use `numpy.linspace` for these cases.

In [111]:
np.arange(0,10,2.2)

array([0. , 2.2, 4.4, 6.6, 8.8])

##### - np.linspace() [np.Function()]

- Return evenly spaced numbers over a specified interval.
- Returns `num` evenly spaced samples, calculated over the interval [`start`, `stop`].
- The endpoint of the interval can optionally be excluded.

In [8]:
np.linspace(start = 1, stop = 10, num=9, endpoint=True, retstep=True, dtype=int, axis= 0)

# Here start defines the starting value of the sequence.
# Here stop defines the end value of the sequence
# Here num defines the number of samples to generate. Default is 50. Must be non-negative.
# Here endpoint defines the If True, `stop` is the last sample. Otherwise, it is not included. Default is True.
# Here If True, return (`samples`, `step`), where `step` is the spacing between samples.

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]), 1.125)

In [11]:
np.linspace(start = 1, stop=10, num=9, endpoint=False, retstep=True, dtype=float, axis = -1)

# Here start defines the starting value of the sequence.
# Here stop defines the end value of the sequence
# Here num defines the number of samples to generate. Default is 50. Must be non-negative.
# Here endpoint defines the If False, `stop` is not the last sample.
# Here If True, return (`samples`, `step`), where `step` is the spacing between samples.

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]), 1.0)

`NOTE : ` Difference between linspace() and arange() function

`linspace()` enables you to control the precise end value where as `arange()` does not allows the control the end value 

##### CREATING ARRAY OF ZEROS

##### - np.zeros() [np.Function()]

- Return a new array of given shape and type, filled with zeros
- `syntax`
        np.zeros(shape, dtype=float, order='C', *, like=None)


In [17]:
##################### CREATING AN 1-D ZEROS ARRAY #####################

np.zeros(shape=4, dtype=float)
# Here 4 defines the number of element to be generated in array
# Here dtype define the datatype of returned array

array([0., 0., 0., 0.])

In [21]:
##################### CREATING AN 2-D ZEROS ARRAY #####################

np.zeros(shape=[2,3], dtype = int)

# Here shape define the shape and dimension of the array
# Here dtype define the datatype of returned array

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
##################### CREATING AN 3-D ZEROS ARRAY #####################

np.zeros(shape = [2,2,3], dtype = int)

# Here shape define the shape and dimension of the array
# Here dtype define the datatype of returned array

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

##### CREATING ARRAY OF ONES

##### - np.ones() [np.function()]

- Return a new array of given shape and type, filled with ones.
- `syntax`
         np.ones(shape, dtype=None, order='C', *, like=None)

In [24]:
##################### CREATING AN 1-D ZEROS ARRAY #####################

np.ones(shape=4, dtype=float)
# Here 4 defines the number of element to be generated in array
# Here dtype define the datatype of returned array

array([1., 1., 1., 1.])

In [25]:
##################### CREATING AN 2-D ZEROS ARRAY #####################

np.zeros(shape=[2,3], dtype = int)

# Here shape define the shape and dimension of the array
# Here dtype define the datatype of returned array

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
##################### CREATING AN 3-D ZEROS ARRAY #####################

np.zeros(shape = [2,2,3], dtype = int)

# Here shape define the shape and dimension of the array
# Here dtype define the datatype of returned array

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

##### CREATING EMPTY ARRAY

##### - np.empty() [np.Function()]

- Return a new array of given shape and type, without initializing entries and with arbitary values.
- `syntax`
            empty(shape, dtype=float, order='C', *, like=None)
- It returns the array of given shape with random values

In [33]:
##################### CREATING AN 1-D EMPTY ARRAY #####################

np.empty(3)

# Here shape define the shape and dimension of the array
# Here dtype define the datatype of returned array

array([ 6.95276429e-310,  6.95276429e-310, -0.00000000e+000])

In [34]:
##################### CREATING AN 2-D EMPTY ARRAY #####################

np.empty(shape = [2,2], dtype = int)

# Here shape define the shape and dimension of the array
# Here dtype define the datatype of returned array

array([[912469920,     32765],
       [912469728,     32765]])

In [36]:
##################### CREATING AN 3-D EMPTY ARRAY #####################

np.empty(shape = [2,2,3], dtype = int)

# Here shape define the shape and dimension of the array
# Here dtype define the datatype of returned array

array([[[4128860, 6029375, 3801155],
        [5570652, 6619251, 7536754]],

       [[7536732, 7077985, 7209077],
        [4259932, 7340144, 6357060]]])

##### CREATING FULL ARRAY

##### - np.full() [np.Function()]

- Return a new array of given shape and type, filled with `fill_value`
- `syntax`
          np.full(shape, fill_value, dtype=None, order='C', *, like=None)

In [40]:
##################### CREATING AN 1-D FULL ARRAY #####################

np.full(shape = [4], fill_value=11, dtype = int)

# Here shape define the shape and dimension of the array
# Here fill_value define the value which is to be fileld
# Here dtype define the datatype of returned array

array([11, 11, 11, 11])

In [42]:
##################### CREATING AN 2-D FULL ARRAY #####################

np.full(shape = [2,2], fill_value=11, dtype = int)

# Here shape define the shape and dimension of the array
# Here fill_value define the value which is to be fileld
# Here dtype define the datatype of returned array

array([[11, 11],
       [11, 11]])

In [43]:
##################### CREATING AN 3-D FULL ARRAY #####################

np.full(shape = [2,2,3], fill_value=11, dtype = int)

# Here shape define the shape and dimension of the array
# Here fill_value define the value which is to be fileld
# Here dtype define the datatype of returned array

array([[[11, 11, 11],
        [11, 11, 11]],

       [[11, 11, 11],
        [11, 11, 11]]])

##### CREATING IDENTITY ARRAY 

##### - np.identity() [np.Function()]

- Return the identity array.
- The identity array is a square array with ones on the main diagonal.
- `syntax`
          np.identity(n, dtype=None, *, like=None)

In [56]:
##################### CREATING AN IDENTITY ARRAY #####################

np.identity((5),dtype = int)

# Here first element `5` defines the range of rows,columns
# Here dtype define the datatype of returned array

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [57]:
np.identity((5,2),dtype = int)

TypeError: 'tuple' object cannot be interpreted as an integer

##### EYE FUNCTION IN IDENTITY MATRIX

##### - np.eye() [np.Function()]

- Return a 2-D array with ones on the diagonal and zeros elsewhere.
- `syntax`
          np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
          
            N : Number of rows in the output.
            M : Number of columns in the output. If None, defaults to `N`.
            k : Index of the diagonal a positive value refers to an upper diagonal, and a          negative value to a lower diagonal.
            dtype : Data-type of the returned array.
            

In [3]:
np.eye(5)

# Here 5 defines that both the rows and columns range 
# np.eye(single element) generate an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
np.eye(4,5,2)

# Here 1st element defines the number of rows
# Here 2nd element defines the  number of columns
# Here 3rd elements define the index of diagonal to be shift to upper side with 2 steps

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.eye(4,5,-2)

# Here 1st element defines the number of rows
# Here 2nd element defines the  number of columns
# Here 3rd elements define the index of diagonal to be shift to lower side with -2 steps

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

##### RESHAPE FUNCTION IN ARRAY

- Reshape() function is used to change the shape of an array without changing its data 
- The function returns a new array with same data but with different shape.
- syntax
            np.reshape(a, newshape, order='C')

In [7]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [12]:
##################### 1-D array reshaping to 2-D array #####################

np.reshape(a,[2,2])

# Here the first element `a` defines the array 
# Here the second element `[2,2]` defines the new array shape which we want

array([[1, 2],
       [3, 4]])

In [13]:
np.reshape(a,[4,1])

array([[1],
       [2],
       [3],
       [4]])

In [14]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
##################### 2-D array reshaping to 2-D array #####################

np.reshape(a,[1,6])
# Here the first element `a` defines the array 
# Here the second element `[1,6]` defines the new array shape which we want

array([[1, 2, 3, 4, 5, 6]])

In [22]:
np.reshape(a,[3,2])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
np.reshape(2,2)

ValueError: cannot reshape array of size 1 into shape (2,)

In [27]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,-1,-2]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 0, -1, -2]]])

In [ ]:
##################### 3-D array reshaping #####################

In [31]:
np.reshape(a,[4,3])

# Here the first element `a` defines the array 
# Here the second element `[4,3]` defines the new array shape which we want

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 0, -1, -2]])

In [39]:
np.reshape(a,[2,3,2])
# Here the first element `a` defines the array 
# Here the second element `[2,3,2]` defines the new array shape which we want

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9,  0],
        [-1, -2]]])

In [35]:
np.reshape(a,[6,2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9,  0],
       [-1, -2]])

In [36]:
np.reshape(a,[1,12])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0, -1, -2]])

In [37]:
np.reshape(a,[12,1])

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [ 0],
       [-1],
       [-2]])

In [38]:
np.reshape(a,[3,2,2])

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9,  0],
        [-1, -2]]])

##### MIN() FUNCTION IN ARRAY

- The min() returns the minimum value present in the array
- syntax
            numpy_array.min(axis=None, out=None, keepdims=False, initial=<no value>, where=True)


In [41]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [42]:
a.min(),b.min(),c.min()

(1000, 1, 0)

##### MAX() FUNCTION IN ARRAY

- The max() returns the maximum value from the array
- syntax
          numpy_array.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)  

In [43]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [44]:
a.max(),b.max(),c.max()

(980000, 8, 45)

##### VAR() FUNCTION IN ARRAY

- The var() returns the variance of all the elements in the array
- syntax
        numpy_array.var(axis=None, dtype=None, out=None, ddof=0, keepdims=False, *, where=True)

In [63]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [46]:
a.var(),b.var(),c.var()

(126930534722.22223, 5.805555555555556, 206.74305555555554)

##### STD() FUNCTION IN ARRAY

- The std() returns the standard deviation of all the elements in the array
- syntax
        numpy_array.std(axis=None, dtype=None, out=None, ddof=0, keepdims=False, *, where=True)

In [64]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [48]:
a.std(),b.std(),c.std()

(356273.1181582779, 2.4094720491334933, 14.378562360526713)

##### NP.SQUARE() FUNCTION IN ARRAY

- The square() returns the square of all the elements in the array
- syntax
        np.square(*args, **kwargs)

In [65]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [52]:
np.square(a)

array([  100000000,     4000000,  2025000000, -1672674304,     1000000,
        1405282704], dtype=int32)

In [53]:
np.square(b)

array([[ 1,  9, 16],
       [36, 49, 64]], dtype=int32)

In [54]:
np.square(c)

array([[[   1,    9,   16],
        [  36,   49,   64]],

       [[ 121,    9, 2025],
        [  25,    0, 1600]]], dtype=int32)

##### NP.POWER() FUNCTION IN ARRAY

- The np.power() returns the power of each element in the array to the given power value
- syntax 
        np.power(*args, **kwargs)

In [66]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [57]:
np.power(a,2)

# Here first element defines the array assigned variable
# Here second element defines the power (ie. x**2)

array([  100000000,     4000000,  2025000000, -1672674304,     1000000,
        1405282704], dtype=int32)

In [58]:
np.power(b,2)

array([[ 1,  9, 16],
       [36, 49, 64]], dtype=int32)

In [59]:
np.power(c,2)

array([[[   1,    9,   16],
        [  36,   49,   64]],

       [[ 121,    9, 2025],
        [  25,    0, 1600]]], dtype=int32)

##### NP.TRANSPOSE() IN ARRAY

- The np.transpose() reverse the dimension of array
- syntax
        np.transpose(a, axes=None)

In [67]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [60]:
np.transpose(a)

array([ 10000,   2000,  45000, 980000,   1000,  75500])

In [61]:
np.transpose(b)

array([[1, 6],
       [3, 7],
       [4, 8]])

In [62]:
np.transpose(c)

array([[[ 1, 11],
        [ 6,  5]],

       [[ 3,  3],
        [ 7,  0]],

       [[ 4, 45],
        [ 8, 40]]])

##### CONCATENATE FUNCTION IN ARRAY

- Join a sequence of arrays along an existing axis.
- syntax
        np.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")



In [69]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [70]:
np.concatenate(a,b)

TypeError: only integer scalar arrays can be converted to a scalar index

`We cannot concatenate the arrays with different dimensions`

In [78]:
##################### concatenating 1-D array  #####################
a = np.array([1,2])
b = np.array([3,4])
a,b

(array([1, 2]), array([3, 4]))

In [80]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [81]:
##################### Concatenating 2-D array  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [82]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [85]:
##################### Concatenating 3-D array  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a,b

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 0,  0],
         [-1, -1]]]),
 array([[[ 5,  6],
         [ 7,  8]],
 
        [[-2, -2],
         [-3, -4]]]))

In [86]:
np.concatenate((a,b))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 0,  0],
        [-1, -1]],

       [[ 5,  6],
        [ 7,  8]],

       [[-2, -2],
        [-3, -4]]])

##### STACK() FUNCTION IN ARRAY

- stack is used to join multiple numpy arrays, unlike concatenate() ,it joins array along a new axis. it returns a numpy array
- To join two arrays they must have same shape and dimensions
- stack() creates a new array which has one more dimension then the input array
        EX -  If we stack 2 1-D arrays then the resultant array will have 2 Dimensions
- syntaxm
        np.stack(arrays, axis=0, out=None)
        
        arrays : sequence of array_like, Each array must have the same shape.

        axis : int, optional, The axis in the result array along which the input arrays are  stacked. 
        1) 0 means the array will stack row wise
        2) 1 means the array will stack column wise

In [89]:
##################### STACKING 1-D array  #####################
a = np.array([1,2])
b = np.array([3,4])
a,b

(array([1, 2]), array([3, 4]))

In [90]:
np.stack((a,b), axis = 0)

array([[1, 2],
       [3, 4]])

In [91]:
np.stack((a,b), axis = 1)

array([[1, 3],
       [2, 4]])

In [92]:
##################### STACKING 2-D array  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [93]:
np.stack((a,b),axis = 0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [94]:
np.stack((a,b),axis = 1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [95]:
##################### STACKING 3-D array  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a,b

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 0,  0],
         [-1, -1]]]),
 array([[[ 5,  6],
         [ 7,  8]],
 
        [[-2, -2],
         [-3, -4]]]))

In [96]:
np.stack((a,b), axis = 0)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 0,  0],
         [-1, -1]]],


       [[[ 5,  6],
         [ 7,  8]],

        [[-2, -2],
         [-3, -4]]]])

In [97]:
np.stack((a,b), axis = 1)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 0,  0],
         [-1, -1]],

        [[-2, -2],
         [-3, -4]]]])

##### V-STACK() FUNCTION IN ARRAY

- vstack() is used to stack the sequence of input array vertically to make a single array
        (The input array is stacked row wise)
- syntax
        np.vstack(tup)

In [102]:
##################### Vertical STACKING 1-D array  #####################
a = np.array([1,2])
b = np.array([3,4])
a,b

(array([1, 2]), array([3, 4]))

In [103]:
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [105]:
##################### Vertical STACKING 2-D array  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [106]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [108]:
##################### Vertical STACKING 3-D array  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a,b

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 0,  0],
         [-1, -1]]]),
 array([[[ 5,  6],
         [ 7,  8]],
 
        [[-2, -2],
         [-3, -4]]]))

In [110]:
np.vstack((a,b))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 0,  0],
        [-1, -1]],

       [[ 5,  6],
        [ 7,  8]],

       [[-2, -2],
        [-3, -4]]])

##### H-STACK FUNCTION IN ARRAY

- hstack() function is used to stack the sequence of input array horizontally (i.e. column wise stacking) to make a single array
- If you are horizontally stacking more than one array then the size of the array may be different or same not an issue
- syntax
        np.hstack(tup)

In [112]:
##################### Horizontal STACKING 1-D array  #####################
a = np.array([1,2])
b = np.array([3,4])
a,b

(array([1, 2]), array([3, 4]))

In [113]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [114]:
##################### Horizontal STACKING 2-D array  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [115]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [116]:
##################### Horizontal STACKING 3-D array  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a,b

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 0,  0],
         [-1, -1]]]),
 array([[[ 5,  6],
         [ 7,  8]],
 
        [[-2, -2],
         [-3, -4]]]))

In [117]:
np.hstack((a,b))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 0,  0],
        [-1, -1],
        [-2, -2],
        [-3, -4]]])

##### FLATTEN ( ) FUNCTION IN ARRAY

- The np.ndarray.flatten() function is used to get a copy of an given array collapsed into on dimension
- This function is useful when we want to convert a multi dimensional
- syntax
        np.ndarray.flatten(array,order='C')

In [119]:
##################### FLATTEN 1-D array  #####################
a = np.array([1,2])
a

array([1, 2])

In [122]:
np.ndarray.flatten(a)

array([1, 2])

In [123]:
##################### FLATTEN 2-D array  #####################
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [124]:
np.ndarray.flatten(a)

array([1, 2, 3, 4])

In [125]:
##################### FLATTEN 3-D array  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 0,  0],
        [-1, -1]]])

In [126]:
np.ndarray.flatten(a)

array([ 1,  2,  3,  4,  0,  0, -1, -1])

### ARRAY ATTRIBUTES

- Attributes are the features/ characterstics of  an object that describe the object

In [127]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

#### SHAPE

- shape returns number of rows and columns in the array

In [128]:
a.shape, b.shape, c.shape

((6,), (2, 3), (2, 2, 3))

#### SIZE

- Size returns the number of elements present in the array

In [129]:
a.size , b.size, c.size

(6, 6, 12)

#### DTYPE

- D-Type returns the type of data along with the size of data in bytes

In [130]:
a.dtype , b.dtype , c.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

#### NDIM

- NDim returns the number of dimensions of the array

In [132]:
a.ndim , b.ndim, c.ndim

(1, 2, 3)

### ARITHEMATIC OPERATIONS ON ARRAY

#### 1) ADDITION

In [134]:
##################### ADDITION OF 1-D ARRAY  #####################
a = np.array([1,2])
b = np.array([3,4])
a,b

(array([1, 2]), array([3, 4]))

In [135]:
a+b

array([4, 6])

In [136]:
##################### ADDITION OF 2-D ARRAY  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [137]:
a+b

array([[ 6,  8],
       [10, 12]])

In [138]:
##################### ADDITION OF 3-D ARRAY  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a,b

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 0,  0],
         [-1, -1]]]),
 array([[[ 5,  6],
         [ 7,  8]],
 
        [[-2, -2],
         [-3, -4]]]))

In [139]:
a+b

array([[[ 6,  8],
        [10, 12]],

       [[-2, -2],
        [-4, -5]]])

#### 2) SUBSTRACTION

In [143]:
##################### SUBSTRACTION OF 1-D ARRAY  #####################
a = np.array([1,2])
b = np.array([3,4])
a,b

(array([1, 2]), array([3, 4]))

In [144]:
a-b

array([-2, -2])

In [145]:
##################### SUBSTRACTION OF 2-D ARRAY  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [146]:
a-b

array([[-4, -4],
       [-4, -4]])

In [147]:
##################### SUBSTRACTION OF 3-D ARRAY  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a,b

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 0,  0],
         [-1, -1]]]),
 array([[[ 5,  6],
         [ 7,  8]],
 
        [[-2, -2],
         [-3, -4]]]))

In [148]:
a-b

array([[[-4, -4],
        [-4, -4]],

       [[ 2,  2],
        [ 2,  3]]])

#### 3) MULTIPLICATION [ Element Wise Multiplication Of Two Arrays ]

In [149]:
##################### MULTIPLICATION OF 1-D ARRAY  #####################
a = np.array([1,2])
b = np.array([3,4])
a,b

(array([1, 2]), array([3, 4]))

In [150]:
a*b

array([3, 8])

In [152]:
##################### MULTIPLICATION OF 2-D ARRAY  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [153]:
a*b

array([[ 5, 12],
       [21, 32]])

In [154]:
##################### MULTIPLICATION OF 3-D ARRAY  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a,b

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 0,  0],
         [-1, -1]]]),
 array([[[ 5,  6],
         [ 7,  8]],
 
        [[-2, -2],
         [-3, -4]]]))

In [155]:
a*b

array([[[ 5, 12],
        [21, 32]],

       [[ 0,  0],
        [ 3,  4]]])

#### 4) MATRIX MULTIPLICATION OF TWO DIFFERENT SHAPE OF MATRIX

In [159]:
##################### MULTIPLICATION OF 1-D ARRAY  #####################
a = np.array([1,2])
b = np.array([3,4])
a.dot(b)

11

In [160]:
a = np.array([1,2])
b = np.array([3,4,5])
a.dot(b)

ValueError: shapes (2,) and (3,) not aligned: 2 (dim 0) != 3 (dim 0)

In [165]:
##################### MULTIPLICATION OF 2-D ARRAY  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a.dot(b)

array([[19, 22],
       [43, 50]])

In [166]:
##################### MULTIPLICATION OF 3-D ARRAY  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a.dot(b)

array([[[[ 19,  22],
         [ -8, -10]],

        [[ 43,  50],
         [-18, -22]]],


       [[[  0,   0],
         [  0,   0]],

        [[-12, -14],
         [  5,   6]]]])

In [168]:
a = np.array([[1,2],[1,2],[1,2]])
b = np.array([[1,2,3],[1,2,3]])
a.dot(b)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [169]:
b.dot(a)

array([[ 6, 12],
       [ 6, 12]])

### INDEXING OF ARRAY

- The elements in the array can be ascessed by the positional index of element
- The index of an array starts from 0 (from left side) and starts from -1 (from right side)

In [4]:
##################### INDEXING OF 1-D ARRAY  #####################
a =np.array((1,2,3,4,5,6))
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a[0],a[1],a[2],a[3],a[4],a[5]

(1, 2, 3, 4, 5, 6)

In [6]:
a[0]+a[5]

7

In [7]:
a[3]*a[5]

24

In [8]:
a[5]/a[1]

3.0

In [11]:
##################### INDEXING OF 2-D ARRAY  #####################
a =np.array(((1,2,3),(4,5,6)))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a[0]

array([1, 2, 3])

In [13]:
a[1]

array([4, 5, 6])

In [14]:
a[0,1]

2

In [18]:
a[1,2]

6

In [19]:
a[1][2]

6

In [21]:
##################### INDEXING OF 3-D ARRAY  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 0,  0],
        [-1, -1]]])

In [22]:
a[0]

array([[1, 2],
       [3, 4]])

In [24]:
a[0,1]

array([3, 4])

In [27]:
a[0,1,0]

3

In [29]:
a[0][1][0]

3

In [25]:
a[0,0]

array([1, 2])

In [26]:
a[0,0,1]

2

In [28]:
a[1]

array([[ 0,  0],
       [-1, -1]])

In [30]:
a[1,0]

array([0, 0])

In [31]:
a[1,0,1]

0

In [32]:
a[1,1]

array([-1, -1])

In [33]:
a[1][1][1]

-1

### SLICING OF ARRAY

In [36]:
##################### SLICING OF 1-D ARRAY  #####################
a = np.array((1,2,3,4,5,6))
a

array([1, 2, 3, 4, 5, 6])

In [37]:
a[:]

array([1, 2, 3, 4, 5, 6])

In [39]:
a[0:]

array([1, 2, 3, 4, 5, 6])

In [40]:
a[2:]

array([3, 4, 5, 6])

In [41]:
a[:-1]

array([1, 2, 3, 4, 5])

In [42]:
a[::-1]

array([6, 5, 4, 3, 2, 1])

In [43]:
a[2:][::-1]

array([6, 5, 4, 3])

In [44]:
##################### SLICING OF 2-D ARRAY  #####################
a =np.array([(1,2),(3,4),(5,6)])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
a[0:]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
a[1:][::-1]

array([[5, 6],
       [3, 4]])

In [47]:
a[1::-1]

array([[3, 4],
       [1, 2]])

In [48]:
a[0:][1]

array([3, 4])

In [49]:
a[:,1][::-1]

array([6, 4, 2])

In [50]:
a[:,1][::-1][2]

2

In [81]:
##################### SLICING OF 3-D ARRAY  #####################
a =np.array([[(1,2,3),(4,5,6)],[(7,3,9),(7,8,9)]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 3, 9],
        [7, 8, 9]]])

In [76]:
a[1:,:2]

array([[[7, 3, 9],
        [7, 8, 9]]])

In [77]:
a[1:2,:]

array([[[7, 3, 9],
        [7, 8, 9]]])

In [78]:
a[1:,1:,1:]

array([[[8, 9]]])

In [79]:
a[0:,1:,1:]

array([[[5, 6]],

       [[8, 9]]])

### ITERATING ARRAY

In [96]:
##################### ITERATING OF 1-D ARRAY  #####################
a=np.array([1,1,1,2,2,2,3,3,3,4,4,4])
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [97]:
for i in a:
    print(i)

1
1
1
2
2
2
3
3
3
4
4
4


##### ANOTHER WAY OF ITERATING AN NUMPY ARRAY BY USING `NP.NDITER()` FUNCTION

In [99]:
list(np.nditer(a))

[array(1),
 array(1),
 array(1),
 array(2),
 array(2),
 array(2),
 array(3),
 array(3),
 array(3),
 array(4),
 array(4),
 array(4)]

In [100]:
for i in np.nditer(a):
    print(i)

1
1
1
2
2
2
3
3
3
4
4
4


In [101]:
##################### ITERATING OF 2-D ARRAY  #####################
a =np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]


In [89]:
for i in a:
    for j in i:
        print(j)

1
2
3
4
5
6


##### ANOTHER WAY OF ITERATING AN NUMPY ARRAY BY USING `NP.NDITER()` FUNCTION

In [102]:
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6


In [103]:
##################### ITERATING OF 3-D ARRAY  #####################

a =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,0,0]]])

In [92]:
for i in a:
    print(i)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [0 0 0]]


In [93]:
for i in a:
    for j in i:
        print(j)

[1 2 3]
[4 5 6]
[7 8 9]
[0 0 0]


In [94]:
for i in a:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
0
0
0


##### ANOTHER WAY OF ITERATING AN NUMPY ARRAY BY USING `NP.NDITER()` FUNCTION

In [104]:
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6
7
8
9
0
0
0


### HOW ARRAYS ARE FASTER THAN LISTS

In [103]:
# Importing the required libraries
import numpy as np
import time

# Declaring size of lists
size=1000000

# Creating lists
l1 = range(size)
l2 = range(size)
# LIST
initialTime = time.time()
result_list = [(a*b) for a,b in zip(l1,l2)]

# Calculating execution time
print('Time taken by List : ',(time.time()-initialTime),' seconds')


Time taken by List :  0.22323155403137207  seconds


In [104]:
# Importing the required libraries
import numpy as np
import time

# Declaring size of arrays
size=1000000

# Creating arrays
a = np.arange(size)
b = np.arange(size)
# ARRAY
initialTime = time.time()
result_array = a*b

# Calculating execution time
print('Time taken by array : ',(time.time()-initialTime),' seconds')

Time taken by array :  0.0040013790130615234  seconds
