# `NUMPY`   

In [1]:
# Following command is used to install the NUMPY 

!pip install numpy

### Imoprting the `Numpy Library`

In [3]:
# Following command is used to import the NUMPY LIBRARY in jupyter notebook

import numpy as np  

# Here the "np" is used as an alias for numpy means np is used as short name for "numpy"

### FUNCTIONS IN NUMPY

##### MIN() FUNCTION IN ARRAY

- The min() returns the minimum value present in the array
- syntax
            numpy_array.min(axis=None, out=None, keepdims=False, initial=<no value>, where=True)


In [41]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [42]:
a.min(),b.min(),c.min()

(1000, 1, 0)

##### MAX() FUNCTION IN ARRAY

- The max() returns the maximum value from the array
- syntax
          numpy_array.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)  

In [43]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [44]:
a.max(),b.max(),c.max()

(980000, 8, 45)

##### VAR() FUNCTION IN ARRAY

- The var() returns the variance of all the elements in the array
- syntax
        numpy_array.var(axis=None, dtype=None, out=None, ddof=0, keepdims=False, *, where=True)

In [63]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [46]:
a.var(),b.var(),c.var()

(126930534722.22223, 5.805555555555556, 206.74305555555554)

##### STD() FUNCTION IN ARRAY

- The std() returns the standard deviation of all the elements in the array
- syntax
        numpy_array.std(axis=None, dtype=None, out=None, ddof=0, keepdims=False, *, where=True)

In [64]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [48]:
a.std(),b.std(),c.std()

(356273.1181582779, 2.4094720491334933, 14.378562360526713)

##### NP.SQUARE() FUNCTION IN ARRAY

- The square() returns the square of all the elements in the array
- syntax
        np.square(*args, **kwargs)

In [65]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [52]:
np.square(a)

array([  100000000,     4000000,  2025000000, -1672674304,     1000000,
        1405282704], dtype=int32)

In [53]:
np.square(b)

array([[ 1,  9, 16],
       [36, 49, 64]], dtype=int32)

In [54]:
np.square(c)

array([[[   1,    9,   16],
        [  36,   49,   64]],

       [[ 121,    9, 2025],
        [  25,    0, 1600]]], dtype=int32)

##### NP.POWER() FUNCTION IN ARRAY

- The np.power() returns the power of each element in the array to the given power value
- syntax 
        np.power(*args, **kwargs)

In [66]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [57]:
np.power(a,2)

# Here first element defines the array assigned variable
# Here second element defines the power (ie. x**2)

array([  100000000,     4000000,  2025000000, -1672674304,     1000000,
        1405282704], dtype=int32)

In [58]:
np.power(b,2)

array([[ 1,  9, 16],
       [36, 49, 64]], dtype=int32)

In [59]:
np.power(c,2)

array([[[   1,    9,   16],
        [  36,   49,   64]],

       [[ 121,    9, 2025],
        [  25,    0, 1600]]], dtype=int32)

##### NP.TRANSPOSE() IN ARRAY

- The np.transpose() reverse the dimension of array
- syntax
        np.transpose(a, axes=None)

In [67]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [60]:
np.transpose(a)

array([ 10000,   2000,  45000, 980000,   1000,  75500])

In [61]:
np.transpose(b)

array([[1, 6],
       [3, 7],
       [4, 8]])

In [62]:
np.transpose(c)

array([[[ 1, 11],
        [ 6,  5]],

       [[ 3,  3],
        [ 7,  0]],

       [[ 4, 45],
        [ 8, 40]]])

##### CONCATENATE FUNCTION IN ARRAY

- Join a sequence of arrays along an existing axis.
- syntax
        np.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")



In [69]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

In [70]:
np.concatenate(a,b)

TypeError: only integer scalar arrays can be converted to a scalar index

`We cannot concatenate the arrays with different dimensions`

In [78]:
##################### concatenating 1-D array  #####################
a = np.array([1,2])
b = np.array([3,4])
a,b

(array([1, 2]), array([3, 4]))

In [80]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [81]:
##################### Concatenating 2-D array  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [82]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [85]:
##################### Concatenating 3-D array  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a,b

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 0,  0],
         [-1, -1]]]),
 array([[[ 5,  6],
         [ 7,  8]],
 
        [[-2, -2],
         [-3, -4]]]))

In [86]:
np.concatenate((a,b))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 0,  0],
        [-1, -1]],

       [[ 5,  6],
        [ 7,  8]],

       [[-2, -2],
        [-3, -4]]])

##### STACK() FUNCTION IN ARRAY

- stack is used to join multiple numpy arrays, unlike concatenate() ,it joins array along a new axis. it returns a numpy array
- To join two arrays they must have same shape and dimensions
- stack() creates a new array which has one more dimension then the input array
        EX -  If we stack 2 1-D arrays then the resultant array will have 2 Dimensions
- syntaxm
        np.stack(arrays, axis=0, out=None)
        
        arrays : sequence of array_like, Each array must have the same shape.

        axis : int, optional, The axis in the result array along which the input arrays are  stacked. 
        1) 0 means the array will stack row wise
        2) 1 means the array will stack column wise

In [89]:
##################### STACKING 1-D array  #####################
a = np.array([1,2])
b = np.array([3,4])
a,b

(array([1, 2]), array([3, 4]))

In [90]:
np.stack((a,b), axis = 0)

array([[1, 2],
       [3, 4]])

In [91]:
np.stack((a,b), axis = 1)

array([[1, 3],
       [2, 4]])

In [92]:
##################### STACKING 2-D array  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [93]:
np.stack((a,b),axis = 0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [94]:
np.stack((a,b),axis = 1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [95]:
##################### STACKING 3-D array  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a,b

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 0,  0],
         [-1, -1]]]),
 array([[[ 5,  6],
         [ 7,  8]],
 
        [[-2, -2],
         [-3, -4]]]))

In [96]:
np.stack((a,b), axis = 0)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 0,  0],
         [-1, -1]]],


       [[[ 5,  6],
         [ 7,  8]],

        [[-2, -2],
         [-3, -4]]]])

In [97]:
np.stack((a,b), axis = 1)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 0,  0],
         [-1, -1]],

        [[-2, -2],
         [-3, -4]]]])

##### V-STACK() FUNCTION IN ARRAY

- vstack() is used to stack the sequence of input array vertically to make a single array
        (The input array is stacked row wise)
- syntax
        np.vstack(tup)

In [102]:
##################### Vertical STACKING 1-D array  #####################
a = np.array([1,2])
b = np.array([3,4])
a,b

(array([1, 2]), array([3, 4]))

In [103]:
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [105]:
##################### Vertical STACKING 2-D array  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [106]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [108]:
##################### Vertical STACKING 3-D array  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a,b

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 0,  0],
         [-1, -1]]]),
 array([[[ 5,  6],
         [ 7,  8]],
 
        [[-2, -2],
         [-3, -4]]]))

In [110]:
np.vstack((a,b))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 0,  0],
        [-1, -1]],

       [[ 5,  6],
        [ 7,  8]],

       [[-2, -2],
        [-3, -4]]])

##### H-STACK FUNCTION IN ARRAY

- hstack() function is used to stack the sequence of input array horizontally (i.e. column wise stacking) to make a single array
- If you are horizontally stacking more than one array then the size of the array may be different or same not an issue
- syntax
        np.hstack(tup)

In [112]:
##################### Horizontal STACKING 1-D array  #####################
a = np.array([1,2])
b = np.array([3,4])
a,b

(array([1, 2]), array([3, 4]))

In [113]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [114]:
##################### Horizontal STACKING 2-D array  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [115]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [116]:
##################### Horizontal STACKING 3-D array  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a,b

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 0,  0],
         [-1, -1]]]),
 array([[[ 5,  6],
         [ 7,  8]],
 
        [[-2, -2],
         [-3, -4]]]))

In [117]:
np.hstack((a,b))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 0,  0],
        [-1, -1],
        [-2, -2],
        [-3, -4]]])

##### FLATTEN ( ) FUNCTION IN ARRAY

- The np.ndarray.flatten() function is used to get a copy of an given array collapsed into on dimension
- This function is useful when we want to convert a multi dimensional
- syntax
        np.ndarray.flatten(array,order='C')

In [119]:
##################### FLATTEN 1-D array  #####################
a = np.array([1,2])
a

array([1, 2])

In [122]:
np.ndarray.flatten(a)

array([1, 2])

In [123]:
##################### FLATTEN 2-D array  #####################
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [124]:
np.ndarray.flatten(a)

array([1, 2, 3, 4])

In [125]:
##################### FLATTEN 3-D array  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 0,  0],
        [-1, -1]]])

In [126]:
np.ndarray.flatten(a)

array([ 1,  2,  3,  4,  0,  0, -1, -1])