# `NUMPY`   

In [1]:
# Following command is used to install the NUMPY 

!pip install numpy

### Imoprting the `Numpy Library`

In [3]:
# Following command is used to import the NUMPY LIBRARY in jupyter notebook

import numpy as np  

# Here the "np" is used as an alias for numpy means np is used as short name for "numpy"

### FUNCTIONS IN NUMPY

##### - np.arange() [np.Function()]

- Return as many possible evenly spaced values within a given interval, the interval include `start` but exclude `stop`
- For integer arguments the function is equivalent to the built-in `range` function, but returns an ndarray rather than a list.
- Returns only 1-D array

In [103]:
np.arange(start = 0, stop = 10, step = 2, dtype = int)

# Here start defines the start value of the range
# Here stop defines the stop value of the range
# Here step defines the difference between the two elements in the array which is to be generated
# Here dtype defines the data type of the returned array

array([0, 2, 4, 6, 8])

In [100]:
np.arange(10,20,2,float)

array([10., 12., 14., 16., 18.])

When using a non-integer step, such as 0.1, the results will often not be consistent.  It is better to use `numpy.linspace` for these cases.

In [111]:
np.arange(0,10,2.2)

array([0. , 2.2, 4.4, 6.6, 8.8])

##### - np.linspace() [np.Function()]

- Return evenly spaced numbers over a specified interval.
- Returns `num` evenly spaced samples, calculated over the interval [`start`, `stop`].
- The endpoint of the interval can optionally be excluded.

In [8]:
np.linspace(start = 1, stop = 10, num=9, endpoint=True, retstep=True, dtype=int, axis= 0)

# Here start defines the starting value of the sequence.
# Here stop defines the end value of the sequence
# Here num defines the number of samples to generate. Default is 50. Must be non-negative.
# Here endpoint defines the If True, `stop` is the last sample. Otherwise, it is not included. Default is True.
# Here If True, return (`samples`, `step`), where `step` is the spacing between samples.

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]), 1.125)

In [11]:
np.linspace(start = 1, stop=10, num=9, endpoint=False, retstep=True, dtype=float, axis = -1)

# Here start defines the starting value of the sequence.
# Here stop defines the end value of the sequence
# Here num defines the number of samples to generate. Default is 50. Must be non-negative.
# Here endpoint defines the If False, `stop` is not the last sample.
# Here If True, return (`samples`, `step`), where `step` is the spacing between samples.

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]), 1.0)

`NOTE : ` Difference between linspace() and arange() function

`linspace()` enables you to control the precise end value where as `arange()` does not allows the control the end value 

##### CREATING ARRAY OF ZEROS

##### - np.zeros() [np.Function()]

- Return a new array of given shape and type, filled with zeros
- `syntax`
        np.zeros(shape, dtype=float, order='C', *, like=None)


In [17]:
##################### CREATING AN 1-D ZEROS ARRAY #####################

np.zeros(shape=4, dtype=float)
# Here 4 defines the number of element to be generated in array
# Here dtype define the datatype of returned array

array([0., 0., 0., 0.])

In [21]:
##################### CREATING AN 2-D ZEROS ARRAY #####################

np.zeros(shape=[2,3], dtype = int)

# Here shape define the shape and dimension of the array
# Here dtype define the datatype of returned array

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
##################### CREATING AN 3-D ZEROS ARRAY #####################

np.zeros(shape = [2,2,3], dtype = int)

# Here shape define the shape and dimension of the array
# Here dtype define the datatype of returned array

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

##### CREATING ARRAY OF ONES

##### - np.ones() [np.function()]

- Return a new array of given shape and type, filled with ones.
- `syntax`
         np.ones(shape, dtype=None, order='C', *, like=None)

In [24]:
##################### CREATING AN 1-D ZEROS ARRAY #####################

np.ones(shape=4, dtype=float)
# Here 4 defines the number of element to be generated in array
# Here dtype define the datatype of returned array

array([1., 1., 1., 1.])

In [25]:
##################### CREATING AN 2-D ZEROS ARRAY #####################

np.zeros(shape=[2,3], dtype = int)

# Here shape define the shape and dimension of the array
# Here dtype define the datatype of returned array

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
##################### CREATING AN 3-D ZEROS ARRAY #####################

np.zeros(shape = [2,2,3], dtype = int)

# Here shape define the shape and dimension of the array
# Here dtype define the datatype of returned array

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

##### CREATING EMPTY ARRAY

##### - np.empty() [np.Function()]

- Return a new array of given shape and type, without initializing entries and with arbitary values.
- `syntax`
            empty(shape, dtype=float, order='C', *, like=None)
- It returns the array of given shape with random values

In [33]:
##################### CREATING AN 1-D EMPTY ARRAY #####################

np.empty(3)

# Here shape define the shape and dimension of the array
# Here dtype define the datatype of returned array

array([ 6.95276429e-310,  6.95276429e-310, -0.00000000e+000])

In [34]:
##################### CREATING AN 2-D EMPTY ARRAY #####################

np.empty(shape = [2,2], dtype = int)

# Here shape define the shape and dimension of the array
# Here dtype define the datatype of returned array

array([[912469920,     32765],
       [912469728,     32765]])

In [36]:
##################### CREATING AN 3-D EMPTY ARRAY #####################

np.empty(shape = [2,2,3], dtype = int)

# Here shape define the shape and dimension of the array
# Here dtype define the datatype of returned array

array([[[4128860, 6029375, 3801155],
        [5570652, 6619251, 7536754]],

       [[7536732, 7077985, 7209077],
        [4259932, 7340144, 6357060]]])

##### CREATING FULL ARRAY

##### - np.full() [np.Function()]

- Return a new array of given shape and type, filled with `fill_value`
- `syntax`
          np.full(shape, fill_value, dtype=None, order='C', *, like=None)

In [40]:
##################### CREATING AN 1-D FULL ARRAY #####################

np.full(shape = [4], fill_value=11, dtype = int)

# Here shape define the shape and dimension of the array
# Here fill_value define the value which is to be fileld
# Here dtype define the datatype of returned array

array([11, 11, 11, 11])

In [42]:
##################### CREATING AN 2-D FULL ARRAY #####################

np.full(shape = [2,2], fill_value=11, dtype = int)

# Here shape define the shape and dimension of the array
# Here fill_value define the value which is to be fileld
# Here dtype define the datatype of returned array

array([[11, 11],
       [11, 11]])

In [43]:
##################### CREATING AN 3-D FULL ARRAY #####################

np.full(shape = [2,2,3], fill_value=11, dtype = int)

# Here shape define the shape and dimension of the array
# Here fill_value define the value which is to be fileld
# Here dtype define the datatype of returned array

array([[[11, 11, 11],
        [11, 11, 11]],

       [[11, 11, 11],
        [11, 11, 11]]])

##### CREATING IDENTITY ARRAY 

##### - np.identity() [np.Function()]

- Return the identity array.
- The identity array is a square array with ones on the main diagonal.
- `syntax`
          np.identity(n, dtype=None, *, like=None)

In [56]:
##################### CREATING AN IDENTITY ARRAY #####################

np.identity((5),dtype = int)

# Here first element `5` defines the range of rows,columns
# Here dtype define the datatype of returned array

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [57]:
np.identity((5,2),dtype = int)

TypeError: 'tuple' object cannot be interpreted as an integer

##### EYE FUNCTION IN IDENTITY MATRIX

##### - np.eye() [np.Function()]

- Return a 2-D array with ones on the diagonal and zeros elsewhere.
- `syntax`
          np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
          
            N : Number of rows in the output.
            M : Number of columns in the output. If None, defaults to `N`.
            k : Index of the diagonal a positive value refers to an upper diagonal, and a          negative value to a lower diagonal.
            dtype : Data-type of the returned array.
            

In [3]:
np.eye(5)

# Here 5 defines that both the rows and columns range 
# np.eye(single element) generate an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
np.eye(4,5,2)

# Here 1st element defines the number of rows
# Here 2nd element defines the  number of columns
# Here 3rd elements define the index of diagonal to be shift to upper side with 2 steps

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.eye(4,5,-2)

# Here 1st element defines the number of rows
# Here 2nd element defines the  number of columns
# Here 3rd elements define the index of diagonal to be shift to lower side with -2 steps

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

##### RESHAPE FUNCTION IN ARRAY

- Reshape() function is used to change the shape of an array without changing its data 
- The function returns a new array with same data but with different shape.
- syntax
            np.reshape(a, newshape, order='C')

In [7]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [12]:
##################### 1-D array reshaping to 2-D array #####################

np.reshape(a,[2,2])

# Here the first element `a` defines the array 
# Here the second element `[2,2]` defines the new array shape which we want

array([[1, 2],
       [3, 4]])

In [13]:
np.reshape(a,[4,1])

array([[1],
       [2],
       [3],
       [4]])

In [14]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
##################### 2-D array reshaping to 2-D array #####################

np.reshape(a,[1,6])
# Here the first element `a` defines the array 
# Here the second element `[1,6]` defines the new array shape which we want

array([[1, 2, 3, 4, 5, 6]])

In [22]:
np.reshape(a,[3,2])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
np.reshape(2,2)

ValueError: cannot reshape array of size 1 into shape (2,)

In [27]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,-1,-2]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 0, -1, -2]]])

In [ ]:
##################### 3-D array reshaping #####################

In [31]:
np.reshape(a,[4,3])

# Here the first element `a` defines the array 
# Here the second element `[4,3]` defines the new array shape which we want

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 0, -1, -2]])

In [39]:
np.reshape(a,[2,3,2])
# Here the first element `a` defines the array 
# Here the second element `[2,3,2]` defines the new array shape which we want

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9,  0],
        [-1, -2]]])

In [35]:
np.reshape(a,[6,2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9,  0],
       [-1, -2]])

In [36]:
np.reshape(a,[1,12])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0, -1, -2]])

In [37]:
np.reshape(a,[12,1])

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [ 0],
       [-1],
       [-2]])

In [38]:
np.reshape(a,[3,2,2])

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9,  0],
        [-1, -2]]])