# `NUMPY`   

In [1]:
# Following command is used to install the NUMPY 

!pip install numpy

### Imoprting the `Numpy Library`

In [3]:
# Following command is used to import the NUMPY LIBRARY in jupyter notebook

import numpy as np  

# Here the "np" is used as an alias for numpy means np is used as short name for "numpy"

### ARRAY ATTRIBUTES

- Attributes are the features/ characterstics of  an object that describe the object

In [127]:
a = np.array([10000,2000,45000,980000,1000,75500])
b = np.array([[1,3,4],[6,7,8]])
c = np.array([[[1,3,4],[6,7,8]],[[11,3,45],[5,0,40]]])
a,b,c

(array([ 10000,   2000,  45000, 980000,   1000,  75500]),
 array([[1, 3, 4],
        [6, 7, 8]]),
 array([[[ 1,  3,  4],
         [ 6,  7,  8]],
 
        [[11,  3, 45],
         [ 5,  0, 40]]]))

#### SHAPE

- shape returns number of rows and columns in the array

In [128]:
a.shape, b.shape, c.shape

((6,), (2, 3), (2, 2, 3))

#### SIZE

- Size returns the number of elements present in the array

In [129]:
a.size , b.size, c.size

(6, 6, 12)

#### DTYPE

- D-Type returns the type of data along with the size of data in bytes

In [130]:
a.dtype , b.dtype , c.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

#### NDIM

- NDim returns the number of dimensions of the array

In [132]:
a.ndim , b.ndim, c.ndim

(1, 2, 3)

### ARITHEMATIC OPERATIONS ON ARRAY

#### 1) ADDITION

In [134]:
##################### ADDITION OF 1-D ARRAY  #####################
a = np.array([1,2])
b = np.array([3,4])
a,b

(array([1, 2]), array([3, 4]))

In [135]:
a+b

array([4, 6])

In [136]:
##################### ADDITION OF 2-D ARRAY  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [137]:
a+b

array([[ 6,  8],
       [10, 12]])

In [138]:
##################### ADDITION OF 3-D ARRAY  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a,b

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 0,  0],
         [-1, -1]]]),
 array([[[ 5,  6],
         [ 7,  8]],
 
        [[-2, -2],
         [-3, -4]]]))

In [139]:
a+b

array([[[ 6,  8],
        [10, 12]],

       [[-2, -2],
        [-4, -5]]])

#### 2) SUBSTRACTION

In [143]:
##################### SUBSTRACTION OF 1-D ARRAY  #####################
a = np.array([1,2])
b = np.array([3,4])
a,b

(array([1, 2]), array([3, 4]))

In [144]:
a-b

array([-2, -2])

In [145]:
##################### SUBSTRACTION OF 2-D ARRAY  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [146]:
a-b

array([[-4, -4],
       [-4, -4]])

In [147]:
##################### SUBSTRACTION OF 3-D ARRAY  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a,b

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 0,  0],
         [-1, -1]]]),
 array([[[ 5,  6],
         [ 7,  8]],
 
        [[-2, -2],
         [-3, -4]]]))

In [148]:
a-b

array([[[-4, -4],
        [-4, -4]],

       [[ 2,  2],
        [ 2,  3]]])

#### 3) MULTIPLICATION [ Element Wise Multiplication Of Two Arrays ]

In [149]:
##################### MULTIPLICATION OF 1-D ARRAY  #####################
a = np.array([1,2])
b = np.array([3,4])
a,b

(array([1, 2]), array([3, 4]))

In [150]:
a*b

array([3, 8])

In [152]:
##################### MULTIPLICATION OF 2-D ARRAY  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [153]:
a*b

array([[ 5, 12],
       [21, 32]])

In [154]:
##################### MULTIPLICATION OF 3-D ARRAY  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a,b

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 0,  0],
         [-1, -1]]]),
 array([[[ 5,  6],
         [ 7,  8]],
 
        [[-2, -2],
         [-3, -4]]]))

In [155]:
a*b

array([[[ 5, 12],
        [21, 32]],

       [[ 0,  0],
        [ 3,  4]]])

#### 4) MATRIX MULTIPLICATION OF TWO DIFFERENT SHAPE OF MATRIX

In [159]:
##################### MULTIPLICATION OF 1-D ARRAY  #####################
a = np.array([1,2])
b = np.array([3,4])
a.dot(b)

11

In [160]:
a = np.array([1,2])
b = np.array([3,4,5])
a.dot(b)

ValueError: shapes (2,) and (3,) not aligned: 2 (dim 0) != 3 (dim 0)

In [165]:
##################### MULTIPLICATION OF 2-D ARRAY  #####################
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a.dot(b)

array([[19, 22],
       [43, 50]])

In [166]:
##################### MULTIPLICATION OF 3-D ARRAY  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
b = np.array([[[5,6],[7,8]],[[-2,-2],[-3,-4]]])
a.dot(b)

array([[[[ 19,  22],
         [ -8, -10]],

        [[ 43,  50],
         [-18, -22]]],


       [[[  0,   0],
         [  0,   0]],

        [[-12, -14],
         [  5,   6]]]])

In [168]:
a = np.array([[1,2],[1,2],[1,2]])
b = np.array([[1,2,3],[1,2,3]])
a.dot(b)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [169]:
b.dot(a)

array([[ 6, 12],
       [ 6, 12]])

### INDEXING OF ARRAY

- The elements in the array can be ascessed by the positional index of element
- The index of an array starts from 0 (from left side) and starts from -1 (from right side)

In [4]:
##################### INDEXING OF 1-D ARRAY  #####################
a =np.array((1,2,3,4,5,6))
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a[0],a[1],a[2],a[3],a[4],a[5]

(1, 2, 3, 4, 5, 6)

In [6]:
a[0]+a[5]

7

In [7]:
a[3]*a[5]

24

In [8]:
a[5]/a[1]

3.0

In [11]:
##################### INDEXING OF 2-D ARRAY  #####################
a =np.array(((1,2,3),(4,5,6)))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a[0]

array([1, 2, 3])

In [13]:
a[1]

array([4, 5, 6])

In [14]:
a[0,1]

2

In [18]:
a[1,2]

6

In [19]:
a[1][2]

6

In [21]:
##################### INDEXING OF 3-D ARRAY  #####################
a = np.array([[[1,2],[3,4]],[[0,0],[-1,-1]]])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 0,  0],
        [-1, -1]]])

In [22]:
a[0]

array([[1, 2],
       [3, 4]])

In [24]:
a[0,1]

array([3, 4])

In [27]:
a[0,1,0]

3

In [29]:
a[0][1][0]

3

In [25]:
a[0,0]

array([1, 2])

In [26]:
a[0,0,1]

2

In [28]:
a[1]

array([[ 0,  0],
       [-1, -1]])

In [30]:
a[1,0]

array([0, 0])

In [31]:
a[1,0,1]

0

In [32]:
a[1,1]

array([-1, -1])

In [33]:
a[1][1][1]

-1

### SLICING OF ARRAY

In [36]:
##################### SLICING OF 1-D ARRAY  #####################
a = np.array((1,2,3,4,5,6))
a

array([1, 2, 3, 4, 5, 6])

In [37]:
a[:]

array([1, 2, 3, 4, 5, 6])

In [39]:
a[0:]

array([1, 2, 3, 4, 5, 6])

In [40]:
a[2:]

array([3, 4, 5, 6])

In [41]:
a[:-1]

array([1, 2, 3, 4, 5])

In [42]:
a[::-1]

array([6, 5, 4, 3, 2, 1])

In [43]:
a[2:][::-1]

array([6, 5, 4, 3])

In [44]:
##################### SLICING OF 2-D ARRAY  #####################
a =np.array([(1,2),(3,4),(5,6)])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
a[0:]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
a[1:][::-1]

array([[5, 6],
       [3, 4]])

In [47]:
a[1::-1]

array([[3, 4],
       [1, 2]])

In [48]:
a[0:][1]

array([3, 4])

In [49]:
a[:,1][::-1]

array([6, 4, 2])

In [50]:
a[:,1][::-1][2]

2

In [81]:
##################### SLICING OF 3-D ARRAY  #####################
a =np.array([[(1,2,3),(4,5,6)],[(7,3,9),(7,8,9)]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 3, 9],
        [7, 8, 9]]])

In [76]:
a[1:,:2]

array([[[7, 3, 9],
        [7, 8, 9]]])

In [77]:
a[1:2,:]

array([[[7, 3, 9],
        [7, 8, 9]]])

In [78]:
a[1:,1:,1:]

array([[[8, 9]]])

In [79]:
a[0:,1:,1:]

array([[[5, 6]],

       [[8, 9]]])

### ITERATING ARRAY

In [96]:
##################### ITERATING OF 1-D ARRAY  #####################
a=np.array([1,1,1,2,2,2,3,3,3,4,4,4])
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [97]:
for i in a:
    print(i)

1
1
1
2
2
2
3
3
3
4
4
4


##### ANOTHER WAY OF ITERATING AN NUMPY ARRAY BY USING `NP.NDITER()` FUNCTION

In [99]:
list(np.nditer(a))

[array(1),
 array(1),
 array(1),
 array(2),
 array(2),
 array(2),
 array(3),
 array(3),
 array(3),
 array(4),
 array(4),
 array(4)]

In [100]:
for i in np.nditer(a):
    print(i)

1
1
1
2
2
2
3
3
3
4
4
4


In [101]:
##################### ITERATING OF 2-D ARRAY  #####################
a =np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]


In [89]:
for i in a:
    for j in i:
        print(j)

1
2
3
4
5
6


##### ANOTHER WAY OF ITERATING AN NUMPY ARRAY BY USING `NP.NDITER()` FUNCTION

In [102]:
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6


In [103]:
##################### ITERATING OF 3-D ARRAY  #####################

a =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,0,0]]])

In [92]:
for i in a:
    print(i)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [0 0 0]]


In [93]:
for i in a:
    for j in i:
        print(j)

[1 2 3]
[4 5 6]
[7 8 9]
[0 0 0]


In [94]:
for i in a:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
0
0
0


##### ANOTHER WAY OF ITERATING AN NUMPY ARRAY BY USING `NP.NDITER()` FUNCTION

In [104]:
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6
7
8
9
0
0
0


### HOW ARRAYS ARE FASTER THAN LISTS

In [103]:
# Importing the required libraries
import numpy as np
import time

# Declaring size of lists
size=1000000

# Creating lists
l1 = range(size)
l2 = range(size)
# LIST
initialTime = time.time()
result_list = [(a*b) for a,b in zip(l1,l2)]

# Calculating execution time
print('Time taken by List : ',(time.time()-initialTime),' seconds')


Time taken by List :  0.22323155403137207  seconds


In [104]:
# Importing the required libraries
import numpy as np
import time

# Declaring size of arrays
size=1000000

# Creating arrays
a = np.arange(size)
b = np.arange(size)
# ARRAY
initialTime = time.time()
result_array = a*b

# Calculating execution time
print('Time taken by array : ',(time.time()-initialTime),' seconds')

Time taken by array :  0.0040013790130615234  seconds
